# sops configuration
# See: https://github.com/Mic92/sops-nix

keys:
  # User keys (for encrypting secrets during development)
  # Convert SSH key to age: nix run nixpkgs#ssh-to-age -- < ~/.ssh/id_ed25519.pub
  - &yann age10zp04uauqx9nvan9jvvpyw82szm87mzugrsjar4p9h704vzml9ksg2me04

  # Host keys (for decrypting secrets at runtime)
  # Get from VM after first boot: ssh freebox-vm "cat /etc/ssh/ssh_host_ed25519_key.pub" | nix run nixpkgs#ssh-to-age
  - &freebox-vm age16zu89k9myqqe0rmgggv0tmfy4vd7wyazugn0cdh9vf47hqgvxgmsvg2d4z

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *yann
          - *freebox-vm  # Uncomment after adding host key above
